[urban-haven]
user = www-data
group = www-data
listen = /run/php/php8.4-fpm-urban-haven.sock
listen.owner = www-data
listen.group = www-data
pm = dynamic
pm.max_children = 20
pm.start_servers = 4
pm.min_spare_servers = 2
pm.max_spare_servers = 8
php_admin_value[memory_limit] = 256M
